### ISSUE TITLE
pkgconfig not available in conda package

### ISSUE THREAD

**Issue by wesm** [conda-forge/re2-feedstock#14]
Tools that rely on pkgconfig cannot find the installed package in `$ENV/lib/pkgconfig`

**Comment by scopatz** [comment]
Hi @wesm - I am a little unclear about what you mean here.  Are you saying downstream tools cannot find re2 via pkg-config?

**Comment by wesm** [comment]
On closer look, it doesn't appear that re2 supports pkgconfig. This is probably something that we should fix upstream in re2. cc @kou

**Comment by kou** [comment]
re2 supports pkg-config (`re2.pc`) with `Makefile` build but doesn't support with CMake build.

If we use `Makefile` instead of CMake, we can support pkg-config.

Or we can support pkg-config by we add pkg-config support to CMake build in upstream.
I've sent an e-mail to re2-dev for this: https://groups.google.com/forum/#!topic/re2-dev/bZmRcjZ1PjY

**Comment by wesm** [comment]
That's fine with me

**Comment by h-vetinari** [comment]
Recent `re2` builds [contain](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Fre2-2023.09.01-he738c6c_0.conda) `lib/pkgconfig/re2.pc`, so closing this as outdated.
